# Generated by Django 2.1.2 on 2018-11-30 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(help_text='question', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Suit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='suit',
            field=models.ForeignKey(help_text='my suit', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Suit'),
        ),
    ]
