# Generated by Django 2.1.2 on 2018-11-30 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='suit',
        ),
        migrations.AddField(
            model_name='suit',
            name='q1',
            field=models.ForeignKey(help_text='question1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q1', to='app.Question'),
        ),
        migrations.AddField(
            model_name='suit',
            name='q2',
            field=models.ForeignKey(help_text='question2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q2', to='app.Question'),
        ),
        migrations.AddField(
            model_name='suit',
            name='q3',
            field=models.ForeignKey(help_text='question3', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q3', to='app.Question'),
        ),
    ]
